# Generated by Django 6.0.7 on 2026-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='OPEN', max_length=20)),
            ],
        ),
    ]
