# Generated by Django 6.0.7 on 2026-07-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kovermap', '0003_add_update_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
    ]
